/*
 *  package   Comlink OpenEMR
 *  link      http://www.open-emr.org
 *  author    Sherwin Gaddis <sherwingaddis@gmail.com>
 *  copyright Copyright (c )2022. Sherwin Gaddis <sherwingaddis@gmail.com>
 *  license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

CREATE TABLE `formato_psiquiatrico_2_form` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`pid` int(11) NOT NULL DEFAULT 0,
`uid` int(11) NOT NULL DEFAULT 0,
`enc_id` int(11) NOT NULL DEFAULT 0,
`fetcha` varchar(255) DEFAULT NULL,
`nacimiento` date DEFAULT NULL,
`edad` varchar(255) DEFAULT NULL,
`nombre` varchar(255) DEFAULT NULL,
`genero` varchar(255) DEFAULT NULL,
`evaluaction` varchar(255) DEFAULT NULL,
`encuentra` text DEFAULT NULL,
`proposito` text DEFAULT NULL,
`hipaa_ley` text DEFAULT NULL,
`fuentes` text DEFAULT NULL,
`si_aplica` text DEFAULT NULL,
`estresores` text DEFAULT NULL,
`estao_civil` varchar(255) DEFAULT NULL,
`ocupacion` varchar(255) DEFAULT NULL,
`lugar_donde` varchar(255) DEFAULT NULL,
`historial_social` text DEFAULT NULL,
`historial_presente` text DEFAULT NULL,
`medica` text DEFAULT NULL,
`hist_alcohol_canti` varchar(255) DEFAULT NULL,
`hist_alcohol_ultimo` varchar(255) DEFAULT NULL,
`hist_alcohol_disfuncion` varchar(255) DEFAULT NULL,
`hist_alcohol_comantarios` varchar(255) DEFAULT NULL,
`hist_cannabis_canti` varchar(255) DEFAULT NULL,
`hist_cannabis_ultimo` varchar(255) DEFAULT NULL,
`hist_cannabis_disfuncion` varchar(255) DEFAULT NULL,
`hist_cannabis_comentarios` varchar(255) DEFAULT NULL,
`hist_cocaina_canti` varchar(255) DEFAULT NULL,
`hist_cocaina_ultimo` varchar(255) DEFAULT NULL,
`hist_cocaina_disfuncion` varchar(255) DEFAULT NULL,
`hist_cocaina_comentarios` varchar(255) DEFAULT NULL,
`hist_opioides_canti` varchar(255) DEFAULT NULL,
`hist_opioides_ultimo` varchar(255) DEFAULT NULL,
`hist_opioides_disfuncion` varchar(255) DEFAULT NULL,
`hist_opioides_comentarios` varchar(255) DEFAULT NULL,
`hist_nicotina_canti` varchar(255) DEFAULT NULL,
`hist_nicotina_ultimo` varchar(255) DEFAULT NULL,
`hist_nicotina_disfuncion` varchar(255) DEFAULT NULL,
`hist_nicotina_comentarios` varchar(255) DEFAULT NULL,
`hist_otros_canti` varchar(255) DEFAULT NULL,
`hist_otros_ultimo` varchar(255) DEFAULT NULL,
`hist_otros_disfuncion` varchar(255) DEFAULT NULL,
`hist_otros_comentarios` varchar(255) DEFAULT NULL,
`historial_previo` text DEFAULT NULL,
`historial_medico` varchar(255) DEFAULT NULL,
`enferemedades` text DEFAULT NULL,
`enfermedad_free_text` varchar(255) DEFAULT NULL,
`medicamentos` text DEFAULT NULL,
`hist_familiar` varchar(255) DEFAULT NULL,
`historial_educacion` text DEFAULT NULL,
`historial_legal` text DEFAULT NULL,
`evaluacion_riesgo` varchar(255) DEFAULT NULL,
`acceso_armas` varchar(255) DEFAULT NULL,
`risk_evaluation` text DEFAULT NULL,
`apariencia` text DEFAULT NULL,
`alucinaciones` text DEFAULT NULL,
`actitud_evaluador` varchar(255) DEFAULT NULL,
`sicomotor` text DEFAULT NULL,
`expresion_verbal` varchar(255) DEFAULT NULL,
`orientacion` text DEFAULT NULL,
`orientacion_text` varchar(255) DEFAULT NULL,
`memoria_inmediata` varchar(255) DEFAULT NULL,
`memoria_reciente` varchar(255) DEFAULT NULL,
`atencion_y_concentracion` varchar(255) DEFAULT NULL,
`juicio` varchar(255) DEFAULT NULL,
`afecto` varchar(255) DEFAULT NULL,
`logico` varchar(255) DEFAULT NULL,
`irrelevante` varchar(255) DEFAULT NULL,
`coherente` varchar(255) DEFAULT NULL,
`proceso_de_pensamiento` text DEFAULT NULL,
`delirios` text DEFAULT NULL,
`ideas_suicidas` varchar(255) DEFAULT NULL,
`ideas_homicidas` varchar(255) DEFAULT NULL,
`ideas_free_text` text DEFAULT NULL,
`apreciacion_education` text DEFAULT NULL,
`signs_symptoms` text DEFAULT NULL,
`diagnoses` text DEFAULT NULL,
`rational_recommended` text DEFAULT NULL,
`education_orientation` text DEFAULT NULL,
`pharmacotherapy` text DEFAULT NULL,
`psychitherapy` text DEFAULT NULL,
`laboratories` text DEFAULT NULL,
`referrals` text DEFAULT NULL,
`followup` text DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;
